### PR TITLE
Remove transient storage and downgrade solidity version

### PR DESCRIPTION
**Pull request by prat-gpt**

### CODE REVIEW

**Review by ElliotFriedman — COMMENTED** [review]
This LGTM, but do we want to not lock the EVM version in the foundry toml so that other EVM versions can be used?

I'm unclear on consequences and tradeoffs of this, but if we are no longer using transient storage, it seems like this could potentially impact the EVM version.

**Comment by prat-gpt** [comment]
> This LGTM, but do we want to not lock the EVM version in the foundry toml so that other EVM versions can be used?
> 
> I'm unclear on consequences and tradeoffs of this, but if we are no longer using transient storage, it seems like this could potentially impact the EVM version.

I think we should not lock the evm version in foundry toml. We should set it to default so that evm version gets chosen as per the compiler version. The project that uses FPS as a submodule will set the evm version and the compiler version and the FPS contracts should compile as per those versions.

I don't think there will be any cons, pro would be that FPS will be compatible with all ^0.8.0 compiler versions and corresponding evm versions. @ElliotFriedman

**Review by anajuliabit — DISMISSED** [review]
lgtm

**Comment by ElliotFriedman** [comment]
> I don't think there will be any cons, pro would be that FPS will be compatible with all ^0.8.0 compiler versions and corresponding evm versions. @ElliotFriedman

ok, that sounds good, please make those changes to the foundry toml file and then I'll go ahead and approve

**Review by anajuliabit — APPROVED** [review]

**Review by ElliotFriedman — APPROVED** [review]
LGTM!

**Pull request merged**
